### ISSUE TITLE
勘误：反射

### ISSUE THREAD

**Issue by luckyzachary** [longjoy/micro-go-book#1]
ch4-feature/reflection/reflection.go
func (hero *Hero) Run() string {
	fmt.Println("I am running at speed " + string(hero.Speed))
	return "Running"
}

应该改为
fmt.Println("I am running at speed ", hero.Speed)

同时书中81页的预期输出
I am running at speed  d
应改为
I am running at speed  100

**Comment by CANGWU** [comment]
非常感谢您的反馈，我为我的疏忽道歉，我们会进行修改。
