### ISSUE TITLE
13章的token认证服务代码里面有个interface的小坑

### ISSUE THREAD

**Issue by SealinGp** [longjoy/micro-go-book#2]
[这行](https://github.com/longjoy/micro-go-book/blob/master/ch13-seckill/oauth-service/service/token_service.go#L204)的语句
`
tokenService.tokenEnhancer != nil
`
这句可能会有个坑,关于Interface跟nil做比较,可能得先转换才能做比较
`
tokenService.tokenEnhancer.(*JwtTokenEnhancer) != nil
`

举个例子:
```
func main() {
	var a1 *a

	b := test{t1:a1}
	fmt.Println(b.isT1())
}

type test struct {
	t1 test1
}
func (this *test)isT1() bool {
	return this.t1 == nil
}

type test1 interface {
	t()
}
type a struct {}
func (this *a)t()  {}
```

以上代码输出false,但是吧
`this.t1 == nil` 改成
`this.t1.(*a) == nil`
后输出true

**Comment by CANGWU** [comment]
```
// 带方法的 interface
type iface struct {
    tab  *itab
    data unsafe.Pointer
}
// 不带方法的 interface
type eface struct {
    _type *_type
    data  unsafe.Pointer
}
```
Golang interface 类型底层实现中存在两种指针，类型指针和值指针，只有当两者都为 nil 的时候，interface 类型的指针才会判断为 nil。

```
var a1 *a
b := test{t1:a1}
```
上述这段代码中，为 `t1 test1 interface` 赋予了一个类型指针，所以 `b.isT1() = false` 会成立
而`this.t1.(*a) == nil` 代码中断言了具体的类型再进行判断，判断 nil 的条件就变为判断值指针即可。

在 `tokenService.tokenEnhancer != nil` 的判断中，`TokenEnhancer interface` 在之前没有赋予过任何的类型指针，此时仅需判断值指针是否存在即可。

确实有可能会出现 `tokenService.tokenEnhancer` 被赋予了类型指针导致其被判断不为 nil 的情况，合理的判断方式应该使用反射判断 interface 是否为 nil 或者在具体实现方法中添加判断，比如：

```
func (enhancer *JwtTokenEnhancer) Enhance(oauth2Token *OAuth2Token, oauth2Details *OAuth2Details) (*OAuth2Token, error) {
       // 此时 enhancer 被指定了具体的类型，可以直接判断
       if enhancer == nil{
           return nil, errors.New("enhancer is nil") 
       }
	return enhancer.sign(oauth2Token, oauth2Details)
}
```

最后非常感谢您的指教，欢迎继续与我们反馈和交流！

**Comment by SealinGp** [comment]
理解了,感谢大佬解答疑惑
